## **1. Give Colab Access to your Google Drive**

In [14]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

## **2: Import the required libraries: Pandas and Numpy**

In [15]:
import pandas as pd
import numpy as np
!pip install ydata-profiling
from ydata_profiling import ProfileReport

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.12/dist-packages (4.17.0)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.15.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.11.10)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.4.4)
Requirement already satisfied: imagehash==4.3.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.1->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.1->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.10.5)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

## **3. Open the Excel with Data**

In [16]:
df = pd.read_excel(r'/content/gdrive/MyDrive/predictive_maintenance_raw.xlsx', header=1)
df

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
0,79.967142,3.926178,36.996777,2389.180538,33.248217,0
1,73.617357,4.909417,34.623168,1724.407142,38.554813,0
2,81.476885,1.601432,30.298152,1590.900558,32.075801,0
3,90.230299,3.562969,26.765316,1998.312771,36.920385,1
4,72.658466,2.349357,33.491117,1914.907689,21.063853,0
...,...,...,...,...,...,...
495,80.389100,2.718900,40.030464,2535.075119,48.132052,1
496,64.627538,4.797687,40.307518,1986.739370,37.210371,0
497,73.096613,3.640843,36.041831,1559.062674,37.202398,0
498,66.243817,2.428821,35.120313,1918.466518,47.903719,0
499,61.172003,3.572583,32.962635,1627.548678,43.400513,0

## **4. Remove any data that isn't appropriate**
*   Any text in numeral columns
*   Any rows with empty cells
*   Any data that is not necessary
*   Any duplicates

In [17]:
df = df.replace(['not recorded', '?', ''], np.nan)
df = df.dropna()
df = df.drop_duplicates()
df = df.drop(columns=[col for col in df.columns if "Unnamed" in col], errors='ignore')

df

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
0,79.967142,3.926178,36.996777,2389.180538,33.248217,0
1,73.617357,4.909417,34.623168,1724.407142,38.554813,0
2,81.476885,1.601432,30.298152,1590.900558,32.075801,0
3,90.230299,3.562969,26.765316,1998.312771,36.920385,1
4,72.658466,2.349357,33.491117,1914.907689,21.063853,0
...,...,...,...,...,...,...
495,80.389100,2.718900,40.030464,2535.075119,48.132052,1
496,64.627538,4.797687,40.307518,1986.739370,37.210371,0
497,73.096613,3.640843,36.041831,1559.062674,37.202398,0
498,66.243817,2.428821,35.120313,1918.466518,47.903719,0
499,61.172003,3.572583,32.962635,1627.548678,43.400513,0

## **5. Remove any unwanted text from data**

In [18]:
df.dtypes

temperature_F     float64
vibration_mm_s    float64
pressure_PSI      float64
runtime_hours     float64
humidity_%        float64
failure             int64
dtype: object

In [19]:
df['temperature_F'] = df['temperature_F'].astype(str).str.replace('F','').astype(float)
df['vibration_mm_s'] = df['vibration_mm_s'].astype(str).str.replace('mm/s','').astype(float)
df['pressure_PSI'] = df['pressure_PSI'].astype(str).str.replace('PSI','').astype(float)
df['runtime_hours'] = df['runtime_hours'].astype(str).str.replace('hours','').astype(float)
df['humidity_%'] = df['humidity_%'].astype(str).str.replace('%','').astype(float)

df

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
0,79.967142,3.926178,36.996777,2389.180538,33.248217,0
1,73.617357,4.909417,34.623168,1724.407142,38.554813,0
2,81.476885,1.601432,30.298152,1590.900558,32.075801,0
3,90.230299,3.562969,26.765316,1998.312771,36.920385,1
4,72.658466,2.349357,33.491117,1914.907689,21.063853,0
...,...,...,...,...,...,...
495,80.389100,2.718900,40.030464,2535.075119,48.132052,1
496,64.627538,4.797687,40.307518,1986.739370,37.210371,0
497,73.096613,3.640843,36.041831,1559.062674,37.202398,0
498,66.243817,2.428821,35.120313,1918.466518,47.903719,0
499,61.172003,3.572583,32.962635,1627.548678,43.400513,0

## **6. Remove outliers**
*   Can interfere with analysis

In [20]:
df['temperature_F'] = pd.to_numeric(df['temperature_F'])
df['vibration_mm_s'] = pd.to_numeric(df['vibration_mm_s'])
df['pressure_PSI'] = pd.to_numeric(df['pressure_PSI'])
df['runtime_hours'] = pd.to_numeric(df['runtime_hours'])
df['humidity_%'] = pd.to_numeric(df['humidity_%'])
df['failure'] = pd.to_numeric(df['failure'])

In [21]:
df.loc[df['temperature_F'] <= 0, 'temperature_F'] = np.nan
df.loc[df['vibration_mm_s'] < 0, 'vibration_mm_s'] = np.nan
df.loc[df['pressure_PSI'] <= 0, 'pressure_PSI'] = np.nan
df.loc[df['runtime_hours'] < 0, 'runtime_hours'] = np.nan
df.loc[(df['humidity_%'] < 0) | (df['humidity_%'] > 100), 'humidity_%'] = np.nan

df = df.dropna()

df

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
0,79.967142,3.926178,36.996777,2389.180538,33.248217,0
1,73.617357,4.909417,34.623168,1724.407142,38.554813,0
2,81.476885,1.601432,30.298152,1590.900558,32.075801,0
3,90.230299,3.562969,26.765316,1998.312771,36.920385,1
4,72.658466,2.349357,33.491117,1914.907689,21.063853,0
...,...,...,...,...,...,...
495,80.389100,2.718900,40.030464,2535.075119,48.132052,1
496,64.627538,4.797687,40.307518,1986.739370,37.210371,0
497,73.096613,3.640843,36.041831,1559.062674,37.202398,0
498,66.243817,2.428821,35.120313,1918.466518,47.903719,0
499,61.172003,3.572583,32.962635,1627.548678,43.400513,0

## **7. Correct any typing errors and inconsistent naming**
*   Aluminum vs Aluminium
*   Polymr, Compos1te

In [22]:
category_map = {
    "Temp_F": "temperature_F",
    "Vibr_mm_s": "vibration_mm_s",
    "Press_PSI": "pressure_PSI",
    "Humid%": "humidity_%",
    "Run_hours": "runtime_hours"
}

df = df.rename(columns=category_map)

df

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
0,79.967142,3.926178,36.996777,2389.180538,33.248217,0
1,73.617357,4.909417,34.623168,1724.407142,38.554813,0
2,81.476885,1.601432,30.298152,1590.900558,32.075801,0
3,90.230299,3.562969,26.765316,1998.312771,36.920385,1
4,72.658466,2.349357,33.491117,1914.907689,21.063853,0
...,...,...,...,...,...,...
495,80.389100,2.718900,40.030464,2535.075119,48.132052,1
496,64.627538,4.797687,40.307518,1986.739370,37.210371,0
497,73.096613,3.640843,36.041831,1559.062674,37.202398,0
498,66.243817,2.428821,35.120313,1918.466518,47.903719,0
499,61.172003,3.572583,32.962635,1627.548678,43.400513,0

In [23]:
df.describe()

,temperature_F,vibration_mm_s,pressure_PSI,runtime_hours,humidity_%,failure
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,75.068380,3.031826,30.542423,2016.593972,39.884836,0.530000
std,9.812532,0.977997,5.051232,492.033063,9.595662,0.499599
min,42.587327,0.303113,15.518723,529.805683,9.804878,0.000000
25%,67.996926,2.404708,26.987852,1694.031919,33.392636,0.000000
50%,75.127971,3.028532,30.599029,1995.543318,39.968477,1.000000
75%,81.367833,3.651242,33.773692,2349.884705,46.691764,1.000000
max,113.527315,5.632382,43.008416,3596.553784,71.099186,1.000000

In [24]:
!pip install ydata-profiling
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Full Data Report")
profile.to_notebook_iframe()  # in Colab or Jupyter

Output hidden; open in https://colab.research.google.com to view.